### ISSUE TITLE
Bug on Mac: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by cyrus2281** [milad2281/Eco-Search#20]
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
at p (/Users/mobini/Workspace/cyrus2281/Echo-Search/out/make/zip/darwin/x64/echo-search.app/Contents/Resources/app/.webpack/main/index.js:1:11294)
at App.<anonymous> (/Users/mobini/Workspace/cyrus2281/Echo-Search/out/make/zip/darwin/x64/echo-search.app/Contents/Resources/app/.webpack/main/index.js:1:11871)
at App.emit (node:events:513:28)

**Comment by cyrus2281** [comment]
Happens the first time the app is opened on mac

**Comment by cyrus2281** [comment]
Issue caused by rapidly clicking on the icon of the app while it's being installed forcing it to open a window while the app is not ready. 
Solution: BE PATIENT while it installs

closing for now till further complains
